#############################################################################
# Makefile for building: Superfacets
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Apr 16 00:16:03 2014
# Project:  Superfacets.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Superfacets.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -fpermissive -O3 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/usr/X11R6/lib -lGLU -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Vertex3D.cpp \
		Vertex2D.cpp \
		Triangle.cpp \
		Timer.cpp \
		segmenter.cpp \
		Reader.cpp \
		normals.cpp \
		meshvisualizer.cpp \
		Edge.cpp \
		dialogs.cpp \
		colormapper.cpp moc_meshvisualizer.cpp \
		moc_dialogs.cpp
OBJECTS       = main.o \
		Vertex3D.o \
		Vertex2D.o \
		Triangle.o \
		Timer.o \
		segmenter.o \
		Reader.o \
		normals.o \
		meshvisualizer.o \
		Edge.o \
		dialogs.o \
		colormapper.o \
		moc_meshvisualizer.o \
		moc_dialogs.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Superfacets.pro
QMAKE_TARGET  = Superfacets
DESTDIR       = 
TARGET        = Superfacets

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Superfacets.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtOpenGL.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Superfacets.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtOpenGL.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Superfacets.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Superfacets1.0.0 || $(MKDIR) .tmp/Superfacets1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Superfacets1.0.0/ && $(COPY_FILE) --parents Vertex3D.h Vertex2D.h Triangle.h Timer.h Sorting.h segmenter.h Reader.h normals.h meshvisualizer.h Mesh.h Edge.h dialogs.h colormapper.h .tmp/Superfacets1.0.0/ && $(COPY_FILE) --parents main.cpp Vertex3D.cpp Vertex2D.cpp Triangle.cpp Timer.cpp segmenter.cpp Reader.cpp normals.cpp meshvisualizer.cpp Edge.cpp dialogs.cpp colormapper.cpp .tmp/Superfacets1.0.0/ && (cd `dirname .tmp/Superfacets1.0.0` && $(TAR) Superfacets1.0.0.tar Superfacets1.0.0 && $(COMPRESS) Superfacets1.0.0.tar) && $(MOVE) `dirname .tmp/Superfacets1.0.0`/Superfacets1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Superfacets1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_meshvisualizer.cpp moc_dialogs.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_meshvisualizer.cpp moc_dialogs.cpp
moc_meshvisualizer.cpp: Reader.h \
		Vertex2D.h \
		Vertex3D.h \
		Mesh.h \
		Sorting.h \
		Edge.h \
		Triangle.h \
		colormapper.h \
		normals.h \
		dialogs.h \
		meshvisualizer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) meshvisualizer.h -o moc_meshvisualizer.cpp

moc_dialogs.cpp: dialogs.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialogs.h -o moc_dialogs.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp segmenter.h \
		normals.h \
		Mesh.h \
		Sorting.h \
		Edge.h \
		Vertex3D.h \
		Vertex2D.h \
		Triangle.h \
		Timer.h \
		Reader.h \
		meshvisualizer.h \
		colormapper.h \
		dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Vertex3D.o: Vertex3D.cpp Vertex3D.h \
		Vertex2D.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vertex3D.o Vertex3D.cpp

Vertex2D.o: Vertex2D.cpp Vertex2D.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vertex2D.o Vertex2D.cpp

Triangle.o: Triangle.cpp Triangle.h \
		Edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Triangle.o Triangle.cpp

Timer.o: Timer.cpp Timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Timer.o Timer.cpp

segmenter.o: segmenter.cpp segmenter.h \
		normals.h \
		Mesh.h \
		Sorting.h \
		Edge.h \
		Vertex3D.h \
		Vertex2D.h \
		Triangle.h \
		Timer.h \
		Reader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o segmenter.o segmenter.cpp

Reader.o: Reader.cpp Reader.h \
		Vertex2D.h \
		Vertex3D.h \
		Mesh.h \
		Sorting.h \
		Edge.h \
		Triangle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Reader.o Reader.cpp

normals.o: normals.cpp normals.h \
		Mesh.h \
		Sorting.h \
		Edge.h \
		Vertex3D.h \
		Vertex2D.h \
		Triangle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o normals.o normals.cpp

meshvisualizer.o: meshvisualizer.cpp meshvisualizer.h \
		Reader.h \
		Vertex2D.h \
		Vertex3D.h \
		Mesh.h \
		Sorting.h \
		Edge.h \
		Triangle.h \
		colormapper.h \
		normals.h \
		dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meshvisualizer.o meshvisualizer.cpp

Edge.o: Edge.cpp Edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Edge.o Edge.cpp

dialogs.o: dialogs.cpp dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogs.o dialogs.cpp

colormapper.o: colormapper.cpp colormapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colormapper.o colormapper.cpp

moc_meshvisualizer.o: moc_meshvisualizer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_meshvisualizer.o moc_meshvisualizer.cpp

moc_dialogs.o: moc_dialogs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogs.o moc_dialogs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

